doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            gestione_tornei:
                is_bundle: false
                dir: '%kernel.project_dir%/src/GestioneTornei/Infrastructure/Entity'
                prefix: 'App\GestioneTornei\Infrastructure\Entity'
                alias: GestioneTornei
            partite:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Partite/Infrastructure/Entity'
                prefix: 'App\Partite\Infrastructure\Entity'
                alias: Partite
            gestione_utenti:
                is_bundle: false
                dir: '%kernel.project_dir%/src/GestioneUtenti/Infrastructure/Entity'
                prefix: 'App\GestioneUtenti\Infrastructure\Entity'
                alias: Utenti
            security:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Security/Infrastructure/Entity'
                prefix: 'App\Security\Infrastructure\Entity'
                alias: Security



when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
